---
- name: Configure new server
  hosts: tennis-hetz
  gather_facts: yes
  become: yes
  vars_files:
    - ./variables/user.vars.yml
    - ./variables/certbot.vars.yml
    - ./variables/zsh.vars.yml
  roles:
    # - user
    # - ssh-pem
    # - ssh
    # - common
    # - zsh
    # - docker
    # - nginx
    - nginx-add-domen
    - certbot
    - nginx-redirect
    # - postgresql
