---
- name: Configure new server
  hosts: web
  gather_facts: no
  become: yes
  vars_files:
    - ./variables/user.vars.yml
    - ./variables/certbot.vars.yml
    - ./variables/zsh.vars.yml
    - ./variables/postgres.vars.yml
    - ./variables/monitoring.vars.yml
  roles:
    # - user
    # - ssh-pem
    # - ssh
    # - common
    # - zsh
    # - docker
    # - nginx
    # - nginx-add-domen
    # - certbot
    # - nginx-redirect
    # - postgresql
    # - postgresql-change-password
    # - postgresql-add-db-and-user
    - monitoring
