---
- name: Cadvisor | Docker compose up
  docker_stack:
    state: present
    name: "{{ stack_name }}"
    compose:
      - version: "3.7"
        services:
          cadvisor:
            image: "google/cadvisor:{{ cadvisor_version }}"
            volumes:
              - /:/rootfs:ro
              - /var/run:/var/run:ro
              - /sys:/sys:ro
              - /var/lib/docker/:/var/lib/docker:ro
              - /dev/disk:/dev/disk/:ro
            ports:
              - "{{ cadvisor_external_port }}:8080"
