---
- name: Prometheus | Send config files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
    owner: "{{ user_name }}"
    group: "{{ user_primary_group }}"
  with_items:
    - src: files/alert_rules.yml
      dest: /tmp/alert_rules.yml
    - src: files/elasticsearch_rules.yml
      dest: /tmp/elasticsearch_rules.yml

- name: Prometheus | Send template files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
    owner: "{{ user_name }}"
    group: "{{ user_primary_group }}"
  with_items:
    - src: templates/prometheus.yml.j2
      dest: /tmp/prometheus.yml

- name: Prometheus | Docker compose up
  docker_stack:
    state: present
    name: "{{ stack_name }}"
    compose:
      - version: "3.7"
        services:
          prometheus:
            restart: on-failure
            image: "prom/prometheus:{{ prometheus_version }}"
            ports:
              - "{{ prometheus_external_port }}:9090"
            volumes:
              - /tmp/alert_rules.yml:/etc/prometheus/alert_rules.yml
              - /tmp/elasticsearch_rules.yml:/etc/prometheus/elasticsearch.rules
              - /tmp/prometheus.yml:/etc/prometheus/prometheus.yml
              - prometheus:/prometheus
            # extra_hosts:
            #   - ne.gitlab.ccnis.uz:10.100.1.246
            #   - ne.vault.ccnis.uz:10.100.1.245
            #   - test.ne.app.ccnis.uz:10.100.1.248
            #   - test.ne.db.ccnis.uz:10.100.1.247
            #   - ne.mon.ccnis.uz:10.100.1.249
            #   - ne.nginx.ccnis.uz:10.100.1.250
            #   - test.pe.db.ccnis.uz:10.100.1.247
            #   - test.cadvisor.app.ccnis.uz:10.100.1.248
        volumes:
          prometheus:
