---
- name: ROLE - Get stack name from server
  include_role:
    name: get_stack_name
  when: get_stack_name_from_server

- name: TASK - Create common devops files
  include_tasks: common-files.yml

- name: TASK - VAULT AGENT
  include_tasks: vault-agent.yml
  when: is_need_vault_agent

- name: TASK - VAULT
  include_tasks: vault.yml
  when: is_need_vault

- name: ROLE - Docker compose for services
  include_role:
    name: service_compose
  when: is_need_services

- name: TASK - Minio
  include_tasks: minio.yml
  when: is_need_minio
