---
- name: Make dir / Touch file {{ item.dest }}
  file:
    path: "{{ item.dest }}"
    state: "{{ item.state }}"
    mode: "0755"
    owner: "{{ user_name }}"
    group: "{{ user_primary_group }}"
  with_items:
    - state: directory
      dest: /var/www/{{ stack_name }}_devops/scripts
    - state: directory
      dest: /var/www/{{ stack_name }}_devops/vault
    - state: directory
      dest: /var/www/{{ stack_name }}_devops/vault_agent
    - state: directory
      dest: /var/www/{{ stack_name }}_devops/vault_agent/credentials
    - state: directory
      dest: /var/www/{{ stack_name }}_devops/vault_agent/config
    - state: directory
      dest: /var/www/{{ stack_name }}_devops/vault_agent/templates
    - state: touch
      dest: /var/www/{{ stack_name }}_devops/vault_agent/credentials/role_id
    - state: touch
      dest: /var/www/{{ stack_name }}_devops/vault_agent/credentials/secret_id
- name: Write to file vault-agent role_id
  shell: echo {{ vault_credentials.role_id }} > /var/www/{{ stack_name }}_devops/vault_agent/credentials/role_id
- name: Write to file vault secret_id
  shell: echo {{ vault_credentials.secret_id }} > /var/www/{{ stack_name }}_devops/vault_agent/credentials/secret_id
- name: VAULT-AGENT | Send template files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
    owner: "{{ user_name }}"
    group: "{{ user_primary_group }}"
  with_items:
    - src: templates/deploy.sh.j2
      dest: /var/www/{{ stack_name }}_devops/scripts/deploy.sh
    - src: templates/make-template.sh.j2
      dest: /var/www/{{ stack_name }}_devops/scripts/make-template.sh
    - src: templates/services.yml.j2
      dest: /var/www/{{ stack_name }}_devops/scripts/services.yml
    - src: templates/vault-agent.yml.j2
      dest: /var/www/{{ stack_name }}_devops/vault/vault-agent.yml
