# before_script:
#   - docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password $CI_REGISTRY_PASSWORD

stages:
  - lint
  - update

lint_yaml:
  stage: lint
  image:
    name: cytopia/yamllint
    entrypoint: ["/bin/ash", "-c"]
  script:
    - yamllint -f colored ./scripts/services.yml

update_env_test:
  image: gitlab.udevs.io:5050/docker/docker:dind
  stage: update
  before_script:
    - eval $(ssh-agent -s)
    - echo "$GITLAB_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - ssh -p $PB_TEST_SSH_PORT -o StrictHostKeyChecking=no $PB_TEST_USER@$PB_TEST_HOST 'bash -s' < ./scripts/deploy.sh staging
  only:
    - staging

update_env_prod:
  image: gitlab.udevs.io:5050/docker/docker:dind
  stage: update
  before_script:
    - eval $(ssh-agent -s)
    - echo "$GITLAB_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - ssh -p $PB_PROD_SSH_PORT -o StrictHostKeyChecking=no $PB_PROD_USER@$PB_PROD_HOST 'bash -s' < ./scripts/deploy.sh master
  only:
    - master
