---
- import_tasks: install-with-apt.yml

- include_tasks: create-cert-standalone.yml
  with_items: "{{ nginx_domains }}"
  loop_control:
    loop_var: cert_item

- import_tasks: renew-cron.yml
  when: certbot_auto_renew
