version: "3.7"

x-logging:
  &loki
  logging:
    driver: loki
    options:
      loki-url: ${LOKI_PATH}
      loki-batch-size: "400"
      loki-retries: "5"
      max-size: "100m"
      max-file: "1"


services:
  vault-agent:
    <<: *loki
    image: hashicorp/vault-enterprise:latest
    restart: always
    ports:
      - "18200:8200"
    volumes:
      - ../vault-agent:/vault-agent:rw
      - secrets:/secrets:rw
    environment:
      VAULT_ADDR: "https://vault.udevs.io"
    entrypoint: "vault agent -log-level=info -config=/vault-agent/config/vault-agent.hcl"

volumes:
  secrets: 