is_need_grafana: no
is_need_prometheus: no
is_need_alertmanager: no
is_need_loki: no
is_need_promtail: no
is_need_node_exporter: yes
is_need_postgres_exporter: no
is_need_mongodb_exporter: no
is_need_redis_exporter: no
is_need_cadvisor: no

# Stack configs
get_stack_name_from_server: no
stack_name: qv

# Grafana configs
grafana_version: "8.3.3"
grafana_admin_password: "fdgdfg"
grafana_external_port: 3000
prometheus_datasources:
  - name: Prometheus-test
    url: http://prometheus:9090
loki_datasources:
  - name: Loki-test
    url: http://loki:3100
data_sources:
  prometheus: yes
  loki: yes
dashboards:
  node_exporter: yes
  postgres_exporter: yes
  cadvisor_exporter: yes

#Prometheus configs
prometheus_version: "v2.33.5"
prometheus_external_port: 9090
prometheus_exporter_monitoring_group: "qurilish_monitoring"
prometheus_exporters:
  - jobname: node
    exporter:
      # - targets: "10.100.1.250:9100"
      # - targets: "10.100.1.249:9100"
      # - targets: "10.100.1.248:9100"
      # - targets: "10.100.1.247:9100"
      # - targets: "10.100.1.246:9100"
      # - targets: "10.100.1.245:9100"
      - targets: "ne.gitlab.ccnis.uz:9100"
      - targets: "ne.vault.ccnis.uz:9100"
      - targets: "test.ne.app.ccnis.uz:9100"
      - targets: "test.ne.db.ccnis.uz:9100"
      - targets: "ne.mon.ccnis.uz:9100"
      - targets: "ne.nginx.ccnis.uz:9100"
  - jobname: postgres
    exporter:
      # - targets: "10.100.1.247:9187"
      - targets: "test.pe.db.ccnis.uz:9187"
  - jobname: cadvisor
    exporter:
      # - targets: "10.100.1.248:8091"
      - targets: "test.cadvisor.app.ccnis.uz:8091"

#Loki configs
loki_version: "1.4.1"
loki_external_port: 3100

#Promtail configs
promtail_version: "1.4.1"
loki_path: "http://{{ ansible_host }}:{{ loki_external_port }}/loki/api/v1/push"

#Node exporter configs
node_exporter_version: "latest"
node_exporter_external_port: 9100

#Postgres exporter configs
postgres_exporter_version: "v0.9.0"
postgres_exporter_external_port: 9187
postgres_exporter_user: "postgres"
postgres_exporter_password: "{{ postgres_password_new }}"
postgres_exporter_host: "{{ ansible_host }}"
postgres_exporter_port: "{{ postgres_port }}"

#Alertmanager configs
alertmanager_version: "latest"
alertmanager_external_port: 9093
bot_token: dfgdfg
chat_id: -625057509
receiver_name: "alertmanager-receiver"

#Cadvisor configs
cadvisor_version: "latest"
cadvisor_external_port: 8091
