is_need_grafana: yes
is_need_prometheus: yes
is_need_alertmanager: yes
is_need_loki: yes
is_need_promtail: yes
is_need_node_exporter: yes
is_need_postgres_exporter: yes
is_need_mongodb_exporter: no
is_need_redis_exporter: no
is_need_cadvisor: yes

# Stack configs
get_stack_name_from_server: no
stack_name: test_stack

# Grafana configs
grafana_version: "8.3.3"
grafana_admin_password: "admin"
grafana_external_port: 3000
prometheus_datasources:
  - name: Prometheus
    url: http://prometheus:9090
loki_datasources:
  - name: Loki
    url: http://loki:3100
dashboards:
  node_exporter: yes
  postgres_exporter: yes
  cadvisor_exporter: yes

#Prometheus configs
prometheus_version: "v2.33.5"
prometheus_external_port: 9090
prometheus_exporter_monitoring_group: "paynet_monitoring"
prometheus_exporters:
  - jobname: node
    exporter:
      - targets: "node-exporter:9100" # ne-paynet.udevs.io:80
      - targets: "test.ne-paynet.udevs.io:80"
      - targets: "ne-paynet.udevs.io:80"
  - jobname: postgres
    exporter:
      - targets: "postgres-exporter:9187" # pe-paynet.udevs.io:80
      - targets: "test.pe-paynet.udevs.io:80"
      - targets: "pe-paynet.udevs.io:80"

#Loki configs
loki_version: "1.4.1"
loki_external_port: 3100

#Promtail configs
promtail_version: "1.4.1"
loki_path: "http://{{ ansible_host }}:{{ loki_external_port }}/loki/api/v1/push"

#Node exporter configs
node_exporter_version: "latest"
node_exporter_external_port: 9100

#Postgres exporter configs
postgres_exporter_version: "v0.9.0"
postgres_exporter_external_port: 9187
postgres_exporter_user: "postgres"
postgres_exporter_password: "{{ postgres_password_new }}"
postgres_exporter_host: "{{ ansible_host }}"
postgres_exporter_port: "{{ postgres_port }}"

#Alertmanager configs
alertmanager_version: "latest"
alertmanager_external_port: 9093
bot_token: sdfsdfsdfsdf
chat_id: 45135
receiver_name: "alertmanager-receiver"

#Cadvisor configs
cadvisor_version: "latest"
cadvisor_external_port: 8091
