---
user_name: ubuntu
user_password: Gh56Fhjk9HgdjHD
user_primary_group: ubuntu
is_user_sudoer: yes
# shu file ni serverdagi  authorized_keys ga qo'shadi
local_ssh_key_file_path: /home/zafar/.ssh/id_rsa.pub

# serverda shu nomli key yaratadi va pub key ni localga jo'natadi.
ssh_key_filename: id_rsa
