---
# Default theme
oh_my_zsh_theme: robbyrussell

# Default plugins
oh_my_zsh_plugins:
  - git
  - zsh-autosuggestions
  - zsh-syntax-highlighting
# Wether to install by default for all specified users.
# May be overridden by `oh_my_zsh_install` under each user.
oh_my_zsh_install: yes

# User configuration
# Important: oh-my-zsh is installed per user so you need to specify the users to install it for.
users:
  - username: "{{user_name}}"
    oh_my_zsh:
      theme: "{{zsh_theme}}"
      plugins:
        - git
        - zsh-autosuggestions
        - zsh-syntax-highlighting
  # - username: example2
  #   oh_my_zsh:
  #     theme: robbyrussell
  #     plugins:
  #       - git
  #       - mvn
  # - username: example3
  #   oh_my_zsh:
  #     install: no
